import { Figtree, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScrollWrapper from "@/components/Lenis";
import "./globals.css";

const figtree = Figtree({
  variable: "--font-figtree",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${geistMono.variable} h-full font-sans antialiased `}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScrollWrapper>
          <Navbar />
          {children}
          <Footer />
        </SmoothScrollWrapper>
        {/* <Toaster
          theme="dark"
          position="top-right"
          toastOptions={{
            style: {
              background: "#1a1a1a",
              border: "1px solid #2a2a2a",
              color: "#fff",
            },
          }}
        /> */}
      </body>
    </html>
  );
}
